import type { FormOverrides } from '@/features/form/model/types/blacklab-params';
import { parseCollocationContext } from '@/features/form/model/types/form-output';
import { isBLCollocationType } from '@/types/blacklabtypes';

/**
 * Whitelist of search parameters that can only be generated by the search form, and not in other parts of the page
 * If the query params of the page url contains any of these, and the value conflicts with the value in the form after it's parsed its own state from the URL,
 * the form will show a warning that the form could not be restored from the URL, and widgets that affect the conflicting parameters will be disabled.
 * Additionally, compiling the form will ignore the form's native outputs for the conflicting parameters, and instead use the values from the URL.
 */
function firstNonEmpty(query: Record<string, unknown>, ...keys: string[]): string | null {
	for (const key of keys) {
		const rawValue = query[key];
		const values = Array.isArray(rawValue) ? rawValue.filter((item): item is string => typeof item === 'string') : typeof rawValue === 'string' ? [rawValue] : [];
		const value = values.find(item => item !== '');
		if (value) return value;
	}
	return null;
}

export function extractSearchFormOverrides(query: Record<string, unknown>, parallelCorpus: boolean): FormOverrides {
	const patt = firstNonEmpty(query, 'patt', 'query');
	const collpatt = firstNonEmpty(query, 'collpatt');
	const filter = firstNonEmpty(query, 'filter');
	const searchfield = parallelCorpus ? firstNonEmpty(query, 'searchfield', 'searchField', 'field') : null;
	const withspans = firstNonEmpty(query, 'withspans');
	const rawColltype = firstNonEmpty(query, 'colltype');
	const colltype = isBLCollocationType(rawColltype) ? rawColltype : null;
	const rawContext = colltype ? firstNonEmpty(query, 'context') : null;
	const parsedContext = rawContext === null ? undefined : parseCollocationContext(rawContext);
	const context = parsedContext == null || typeof parsedContext === 'number' ? parsedContext : `${parsedContext[0]}:${parsedContext[1]}`;
	const within = firstNonEmpty(query, 'within');
	const reltype = firstNonEmpty(query, 'reltype');
	const annotation = firstNonEmpty(query, 'annotation');
	const rawSensitive = firstNonEmpty(query, 'sensitive');
	const sensitive = rawSensitive === 'true' ? true : rawSensitive === 'false' ? false : undefined;
	return {
		...(patt ? { patt } : {}),
		...(collpatt ? { collpatt } : {}),
		...(filter ? { filter } : {}),
		...(searchfield ? { searchfield } : {}),
		...(withspans === 'true' ? { withspans: true as const } : {}),
		...(colltype ? { colltype } : {}),
		...(context !== undefined ? { context } : {}),
		...(within ? { within } : {}),
		...(reltype ? { reltype } : {}),
		...(annotation ? { annotation } : {}),
		...(sensitive !== undefined ? { sensitive } : {}),
	};
}
