<h2>About the BlackLab Frontend</h2>
<p>
	The software powering this website was developed at the <a href="https://ivdnt.org" target="_blank">Dutch Language Institute</a>. The corpus search is powered by
	<a href="https://github.com/instituutnederlandsetaal/BlackLab" target="_blank">BlackLab</a>, an open source Lucene-based corpus retrieval engine allowing fast and complex searches on large volumes
	of annotated text.
</p>
